[build]
  command = "npm install && cd front && npm install && npm run build"
  publish = "front/dist"
  functions = "netlify/functions"

[dev]
  command = "cd front && npm run dev"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 